module AwsHelpers
  module CloudFormation

    CREATE_COMPLETE = 'CREATE_COMPLETE'
    DELETE_COMPLETE = 'DELETE_COMPLETE'
    ROLLBACK_COMPLETE = 'ROLLBACK_COMPLETE'
    UPDATE_COMPLETE = 'UPDATE_COMPLETE'
    UPDATE_ROLLBACK_COMPLETE = 'UPDATE_ROLLBACK_COMPLETE'

    CREATE_IN_PROGRESS = 'CREATE_IN_PROGRESS'
    UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS'
    DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS'

    CREATE_FAILED = 'CREATE_FAILED'
    DELETE_FAILED = 'DELETE_FAILED'
    UPDATE_FAILED = 'UPDATE_FAILED'
    ROLLBACK_FAILED = 'ROLLBACK_FAILED'
    UPDATE_ROLLBACK_FAILED = 'UPDATE_ROLLBACK_FAILED'

  end
end